services:
  movies-db:
    image: mongo:7.0
    container_name: movies-db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  catalog-db:
    image: mongo:7.0
    container_name: catalog-db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - catalog-data:/data/db
    restart: unless-stopped

volumes:
  mongodata:
  catalog-data:
